twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    #pour utiliser le theme de formulaire bootstrap:
    form_themes: ['bootstrap_4_layout.html.twig']
